<a href="https://colab.research.google.com/github/sabrinaMKE201073/Python-for-Data-Science-Lesson/blob/main/LESSON_DAY_3_(2D_Numpy_Arrays).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Module 5 - Working with Numpy Arrays**

- **2D Numpy Arrays**

In [ ]:
import numpy as np
a = [[11,12,13],[21,22,23],[31,32,33]]
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
#attribute
print(A.ndim)
print(A.shape)
print(A.size)

2
(3, 3)
9


In [ ]:
A[0][1]  #number in row 1, column 2

12

In [ ]:
A[2][1]   #number in row 3, column 2

32

In [ ]:
A[0][0]   #number in row 1, coloumn 1

11

In [ ]:
A[2][2]   #number in row 3, column 3

33

In [ ]:
#slicing method in numpy arrays
A [0:2, 0:2]

array([[11, 12],
       [21, 22]])

In [ ]:
A [0:2, 2]

array([13, 23])

In [ ]:
#Addition of two matrices
X = np.array([[1,0],[0,1]])
Y = np.array([[2,1],[1,2]])
Z = X+Y
Z

array([[3, 1],
       [1, 3]])

In [ ]:
#multiply each Y matrix by 2
2*Y

array([[4, 2],
       [2, 4]])

In [ ]:
#multipy X and Y matrices
Z = X*Y
Z

array([[2, 0],
       [0, 2]])

In [ ]:
#DOT MULTIPLICATION PRODUCT of TWO matrices
A = np.array([[0,1,1],[1,0,1]])
B = np.array([[1,1],[1,1],[-1,1]])
C = np.dot(A,B)
C


array([[0, 2],
       [0, 2]])

In [ ]:
# Calculate the sine of Z
np.sin(Z)

array([[0.90929743, 0.        ],
       [0.        , 0.90929743]])

In [ ]:
#Calculate the transposed matrix T

# 1st, Create a matrix C
C = np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [ ]:
# 2nd, Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])

QUIZ:
- Consider the following list a, convert it to Numpy Array.
- a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
A = np.array(a)
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
#Calculate the numpy array size.
A.size

12

In [ ]:
#Access the element on the first row and first and second columns.
A[0][0:2]

array([1, 2])

QUIZ:
- Perform matrix multiplication with the numpy arrays A and B.

- B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

In [ ]:
B = np.array([[0, 1], [1, 0], [1, 1], [-1, 0]])

C = np.dot(A,B)
C

array([[ 1,  4],
       [ 5, 12],
       [ 9, 20]])

In [ ]:
A = np.array([[1,2],[3,4],[5,6],[7,8]])
A

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])